export interface IApplication {
    applicationId:number
    studentId:number
    instituteId:number
    religion:string
    community:string
    fathername:string
    mothername:string
    annualIncome:number
    instituteName:string
    presentCourse:string
    presentCourseYear:string
    modeOfStudy:string
    classStartDate:Date
    universityBoardName:string
    previousCourse:string
    previousPassingYear:string
    previousCoursePercentage:number
    rollNumber10th:number
    boardName10th:string
    passingYear10th:string
    percentage10th:number
    rollNumber12th:number
    boardName12th:string
    passingYear12th:string
    percentage12th:number
    admissionFee:number
    tuitionFee:number
    otherFee:number
    isDisabled:string
    disabilityType:string
    disabilityPercentage:number
    maritalStatus:string
    parentsProfession:string
    state:string
    district:string
    address:string
    pincode:number
    scholarshipId:number
}
