export interface IInstitute {
    instituteId:number
    instituteCategory:string
    name:string
    institutecode:number
    disecode:number
    location:string
    instituteType:string
    affiliatedState:string
    affiliatedName:string
    admissionStartYear:string
    password:string
    address:string
    city:string
    state:string
    district:string
    pincode:number
    principalName:string
    principalNumber:string
}